### ISSUE TITLE
Option to add names to the output of confusionMatrix()

### ISSUE THREAD

**Issue by lewinfox** [JackStat/ModelMetrics#34]
Hi, thanks for this super helpful package!

I often get confused (no pun intended) as to which axis of the confusion matrix is which, particularly because some packages (e.g `h2o`) use different conventions.

How would you feel about adding an option to `confusionMatrix()` to add dimnames to the result?

```r
actual <- c(0, 0, 1)
predicted <- c(1, 0, 1)

# The current default behaviour is unchanged
confusionMatrix(actual, predicted)
#>      [,1] [,2]
#> [1,]    1    0
#> [2,]    1    1

# But we can add labels if desired
confusionMatrix(actual, predicted, use_names = TRUE)
#>             actual_0 actual_1
#> predicted_0        1        0
#> predicted_1        1        1
```

If you think this has value I have an implementation [here](https://github.com/lewinfox/ModelMetrics/tree/feature/named-cm) and can submit a PR for review.

Thanks!

**Comment by JackStat** [comment]
Sounds good. open a PR

Tyler
________________________________
From: Lewin Appleton-Fox ***@***.***>
Sent: Sunday, March 28, 2021 7:00:55 PM
To: JackStat/ModelMetrics ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JackStat/ModelMetrics] Option to add names to the output of confusionMatrix() (#34)


Hi, thanks for this super helpful package!

I often get confused (no pun intended) as to which axis of the confusion matrix is which, particularly because some packages (e.g h2o) use different conventions.

How would you feel about adding an option to confusionMatrix() to add dimnames to the result?

actual <- c(0, 0, 1)
predicted <- c(1, 0, 1)

# The current default behaviour is unchanged
confusionMatrix(actual, predicted)
#>      [,1] [,2]
#> [1,]    1    0
#> [2,]    1    1

# But we can add labels if desired
confusionMatrix(actual, predicted, use_names = TRUE)
#>             actual_0 actual_1
#> predicted_0        1        0
#> predicted_1        1        1

If you think this has value I have an implementation here<https://isolate.menlosecurity.com/1/3735926911/https://github.com/lewinfox/ModelMetrics/tree/feature/named-cm> and can submit a PR for review.

Thanks!
